apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCsR07A2r1v096ZbQ6RU9DQlLjoZd7gL8nD3LKR7GtLjyz/KCiRNaaFWsg28JI84BZZGbA01Jwf68vsfFRsRfUkLsTPyEdqac3B1jiOAPUMNe/QCifZ9gh5xS/DjleEION/YZR5nP6akYtxIK901YShSR4y5cGwK54xsm5pdU/Qdsts4ZyVIFchSm6z4/8ZalSYVL8s5F2Xc8OmbYqzDKYOLH12MXJoBjls3+6GAelUtcBHMdT7euIS3FpJ5ASReZnFdEleTicSuIc20PwTeFEktFKrUMkvDZgQUyGwIyR/jiJDteBJUijlepavfUuOavYwzlLFUIAE36IJCzncQtyotVLVszkPxJefHkLlQe82yGp3pQDxECP+so6G2Tzgtyn7VF+2tWG7yrLEDppH5MN2av7aAGJTYVHh1o3cv7DRQE2vBZmsmMbO2rUMauFfNR41hH0l+0UWSl9bKPvWwN3z9nLjsnQEoJ+I7OpHxZMztvOCIQAX4cWi2JIxpBqmWOKLu5gkrzTWLVQQ9WmeO6thBA1KR7UDH4w+NoEZDaVcc6WtwSFnQsQ14ByaUkSuCny2ZqM799lUjZcMoBXV7YhuxYQmxNhVX7/G3EwpyRj5av5lsSOkNvn3PCqVVzFJ92JG5M78/lnLsJfSEgj5lhnP6JncDEZQ6nXf41LaAGmcY/Xuo3RWDmkp3lJd2W68rPzihyLF9/jPujlzy6SlOFpXM0yLWA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
