apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-a-long-environment-name-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBgcRzUOktTaLM3C7u4dFhwpc5qSUCYeKLGGZU0Lag1nDgN4bgxIfLmwTqIbL6kyeeu5prExYzdqPzt48YPqBMrTDNSazaB0re00UtGo+aJ27+vArQB6apPr1a5xTytKtA8E9id5KPT6tdRQndsldl9wZyv8ePmc8rB49niXZV5Y2tF0INHS6yOeob2Xf7Se3B+nFbDDkg2AIECHZoR3lZZTYqPuX3qz0Hfv0Cloq2wmBP2nADKNK+S8Y5yZoEJg8rcZGGyzwalpvvvSuER7Ax5ztmFFuZCGrIkcm1q8cu9c0PIFIULBU5ZrbjYO3akInv1cgC8wa0A4R1ryr+UFTckbQ75CKWnhQaGYGizZS/5Kgm5iLvZjVDYPdKCgTQu1EPqQGZwqo+Pw2ML1k0B2Ci3Wa91N9PR4P91lrx1T1pDc2SpPHe2yNImF1lrFtRVTctaDIGVtcZ8Ht5JXATCikUBHsNNL8dZfT4mRC8871YFgvcVG5CUJdkKBGJa7hKoAHpYbI5kcFWC7TuzNkmAzGMeSz1raGR+aUKcJligjDfaLS9aoJCt2wL6XBKwWob4AKa211dOpzyvOBNCeyW5n2LvtkMuDp9LaATrDwE4E+jaMVTVNy0hET3X1eWxl/JwyXBbJakUe5cXOMIK/QQhA56JgFbqsApuuHDPO4+FsMRmXfxgdBPIb7BA5KXBcYR3Xx/8kq9Cz3T1mjnVixQSDwoVA1huTQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-a-long-environment-name-taxi
      namespace: cicd
    type: Opaque
