apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBUsb+Exo+2KS4/owb6QD8km1bTA7CIVlCaeoJI6s4s/B85XuotU5/iLz9F0CJphk74m9j/veuC666DdEHLgyltLbApopIYwOke4aAimp3XVF3l4U+oUTiVGD+BzvpcscxTlOZ7dgUy6L0D2JdDPDiuvPHcR4GDKzEoVEVLWX8+6tnmgneHTx6dsn4R+YJFZauIQd7Wg0QZfo7eVWbGtuYTSdMP94rlY4x2qyIozE1ynot9B9l6dPXv+1QjUEg44zSi0XK7YWPmDMLXNg0sOlO/t9ia61Xze2ryc2wsx7aNH/dHjvA4BP4dPWfLrU5YfWbsuDINwdIuXqp0omaiXL0JiVEUc+eeEWgYDjMUYm4skbTh+867upqdtxx4OICpEiuPJf8xAmGTggsQRJ7U1Rj49RCdcoPPqqXMB5hpyrZSKzOe19KY57wsjwPZYYbio9MkrR7Cp7hqqrBsqIc58JapGZBko54tJhnrRTMhhcvhT1HDaIMWhorCn+4TKfXU/zYSk+KfNXQRSpYh27utXrZV59i44JRFFcqSCApoiU6Slr8pp1dR71+ScwuSRz2XK/Er7jqrnp5uexCrpkTEhY1DtV7vBygUSQJ9HnkQNiqhSIo6kKO16wCOS33Owsf0H6ZtKNqHdp5vIe+laY046+HU5kpzNhoC0hK5k4Btv+8zCMfDmlYtNmmEIfC4OOLmqbMJrSZZA3d0qwJuBaozii5BKoTDtw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
