apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: cicd
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'keithchong/gitops2')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-a-long-environment-name-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'keithchong/taxi')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-anotherverylongenvname-taxi2
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'keithchong/taxi2')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-taxi2
    template:
      name: app-ci-template
  - bindings:
    - ref: dev-app-taxi-taxi-binding
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-dev-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'keithchong/taxi')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
