apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/keithchong/gitops2.git?ref=main
  creationTimestamp: null
  name: a-long-environment-name
spec: {}
status: {}
